routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/','FrontendController@index');

//Controladores temporales para presentacion
Route::get('/panel', 'AdminController@panel');
Route::get('/reservas', 'AdminController@bookings');
Route::get('/subirPropiedad', 'AdminController@submitProperties');
Route::get('/miPerfil', 'AdminController@myProfile');
Route::get('/listproporties', 'PropertyFilterController@propertyList');



Route::get('/listproporties', 'PropertyFilterController@propertyList');


Route::get('/contacto', 'AdminController@contacto');

Route::resource('/propiedades', 'PropertyController');

Route::resource('Multimedia', 'MultimediaController');
Route::get('/Main', 'MultimediaController@indexMain');
Route::post('/imageMain/{id}/{name}', 'MultimediaController@storeMain');


//ruta de de carga de combos
Route::get('/{id}/get_provinces', 'LocationController@getProvincesByCountry');
Route::get('/{id}/get_localities', 'LocationController@getLocalitiesByProvince');
Route::get('/{id}/get_cities', 'LocationController@getCitiesByLocalitie');



Auth::routes();

// Rutas de usuaruaio para Registrarse, loguearse, desloguearse y editar el perfil
Route::get('/loginUser', 'UserController@login');
Route::post('/login', 'UserController@authenticate' );
Route::get('/logout', 'UserController@logout');
Route::get('/register', 'UserController@showRegistrationForm');
Route::post('/register', 'UserController@register' );
Route::get('/usuario/perfil', 'AdminController@myProfile')->name('user.perfil');;
Route::post('/usuario/perfil', 'AdminController@storeProfile');
Route::post('/usuario/changepass', 'AdminController@changePassword');
Route::post('/usuario/social', 'AdminController@socialNetwork');
// Ruta para procesar los comentarios enviados
Route::post('/propiedades/comment/{propiedad}', 'PropertyController@commentStore');
// Ruta princiipal de los mensajes
Route::get('/mensajes', 'MessageController@index');
Route::post('/mensajes/respuesta', 'MessageController@replyStore');
 //searches
Route::post('/searches-list', 'SearchesController@index')->name('system.searches-list');

//System Groups
Route::prefix('system')->group(function(){
    Route::get('/login','Auth\SystemLoginController@showLoginForm')->name('system.login');
    Route::post('/login','Auth\SystemLoginController@login')->name('system.login.submit');
    Route::post('/system','SystemsController@guardarUsers')->name('system.users.save');
    Route::get('/','SystemsController@index')->name('system.dashboard');
    Route::get('/roles','RoleController@getRoles')->name('system.roles');
    Route::get('/users','SystemsController@getUsers')->name('system.users');
    Route::get('/list-users','SystemsController@index')->name('system.list-users');
    Route::get('/setting','SystemsController@indexSetting')->name('system.setting');
    //country
    Route::get('/country', 'CountryController@index')->name('system.country');
    Route::post('/country', 'CountryController@store')->name('system.country.save');
    Route::put('/country', 'CountryController@edit')->name('system.country.update');
    //cities
    Route::get('/cities', 'CityController@index')->name('system.cities');
    Route::get('/cities/search', 'CityController@search')->name('system.cities.search');
    Route::post('/cities', 'CityController@store')->name('system.cities.save');
    Route::put('/cities', 'CityController@edit')->name('system.cities.update');
    Route::delete('/cities', 'CityController@destroy')->name('system.cities.delete');
    //provinces
    Route::get('/province','ProvinceController@index')->name('system.province');
    Route::get('/province/list','ProvinceController@list')->name('system.province.list');
    Route::post('/province','ProvinceController@store')->name('system.province.save');
    Route::put('/province','ProvinceController@edit')->name('system.province.update');
    Route::delete('/province','ProvinceController@destroy')->name('system.province.delete');
    //localities
    Route::get('/localities','LocalitieController@index')->name('system.localities');
    Route::get('/localities/list','LocalitieController@list')->name('system.localities.list');
    Route::get('/localities/search', 'LocalitieController@search')->name('system.localities.search');
    Route::post('/localities','LocalitieController@store')->name('system.localities.save');
    Route::put('/localities','LocalitieController@edit')->name('system.localities.update');
    Route::delete('/localities','LocalitieController@destroy')->name('system.localities.delete');
    Route::get('/logout','Auth\SystemLoginController@logout')->name('system.logout');
    Route::put('/udpate','SystemsController@update')->name('system.update');
   
});

app/Http/Controllers/PropertyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Alertify;
use App\Realestate;
use App\Option;
use App\Country;
use App\Province;
use App\Localitie;
use App\City;
use App\State;
use App\TypeOfRealestate;
use App\Realestate_option;
use App\User;
use App\Contact;
use App\Comment;

class PropertyController extends Controller
{
    private $properties;
     public function __construct()
      {
        $this->middleware('auth', ['except' => ['show','propertyList']] );
      }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {  
        $properties = Realestate::where('user_id', auth()->id())->get();
        $countComments = $this->countComment() ;

        return view('frontend.dashboard.property.index', compact('properties','countComments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $countComments     = $this->countComment() ;
        $idUser            = auth()->id();
        $user              = User::find($idUser);
        $options           = Option::all();
        $countries         = Country::all();
        $provinces         = Province::all();
        $localities        = Localitie::all();
        $cities            = City::all();
        $states            = State::all();
        $typeOfRealestates = TypeOfRealestate::all();
        $celular           = $user->contact()->where('type_of_contact_id', 1)->get();


        
        return view('frontend.dashboard.property.create', compact('options','countries','provinces','localities','cities','states','typeOfRealestates','celular','countComments'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $data = request()->validate([
            'propertyName'        => 'required',
            'price'               => 'required',
            'area'                => 'required',
            'bedrooms'            => 'required',
            'bathrooms'           => 'required',
            'address'             => 'required',
            'city_id'             => 'required',
            'country_id'          => 'required',
            'province_id'         => 'required',
            'state_id'            => 'required',
            'detailedInformation' => 'required',
            'name'                => 'required',
            'email'               => 'required',
            'phone'               => 'required',
            
        ], [
            'propertyName.required'  => 'Porfavor cargar un nombre',
            'price.required'         => 'Porfavor cargar un precio',
            'area.required'          => 'Porfavor cargar el área',
            'bedrooms.required'      => 'Porfavor cargar número de habitaciones',
            'bathrooms.required'     => 'Porfavor cargar número de baños',
            'address.required'       => 'Porfavor cargar dirección',
            'city_id.required'       => 'Porfavor cargar barrio',
            'country.required'       => 'Porfavor cargar pais',
            'province.required'      => 'Porfavor cargar provincia',
            'state.required'         => 'Porfavor cargar localida / estado',
            'detailedInformation'    => 'Porfavor cargar información detallada',
            'name.required'          => 'Porfavor cargar nombre',
            'email.required'         => 'Porfavor cargar email',
            'phone.required'         => 'Porfavor cargar teléfono',
            
            
        ]);

        $idUser                            = auth()->id();
        // modelo realestate
        $realestate                        = new Realestate;
        $realestate->name                  = $request->propertyName;
        $realestate->price                 = $request->price;
        $realestate->area                  = $request->area;
        $realestate->bedrooms              = $request->bedrooms;
        $realestate->bathrooms             = $request->bathrooms;
        $realestate->address               = $request->address;
        $realestate->detailedInformation   = $request->detailedInformation;   
        $realestate->state_id              = $request->state_id;
        $realestate->type_of_realestate_id = $request->typeOfRealestate_id;
        $realestate->latitude              = $request->latitude;
        $realestate->longitude             = $request->longitude;
        $realestate->country_id            = $request->country_id;
        $realestate->province_id           = $request->province_id;
        $realestate->locality_id           = $request->localitie_id;
        $realestate->city_id               = $request->city_id;
        $realestate->user_id               = $idUser;
        //  modeo contact
        $user                              = User::findorFail($idUser);
        $userCelular                       = New Contact;
        $userCelular->contact              = $request->phone;
        $userCelular->type_of_contact_id   = 1;
        $user->contact()->save($userCelular);
        
        if($realestate->save())
        {
            // Despues de guardar la propiedad, guardamos las especificaciones
            if (isset($request->specifics)) {
                $realestate_lastInsert                = Realestate::where('user_id', $idUser )->get()->last();
                $specifics                            = $request->specifics;

                foreach ($specifics as $specific) {
                    $realestate_option                = New Realestate_option;
                    $realestate_option->realestate_id = $realestate_lastInsert->id; 
                    $realestate_option->option_id     = $specific;
                    $realestate_option->save();
                }
                
            }

            return redirect('Multimedia/'.$realestate->id.'')
                    ->with('typemsg', 'success')
                    ->with('message', 'Item creado correctamente.');
        }
        else {
            return redirect('frontend.dashboard.submitProperties')
                    ->with('typemsg', 'error')
                    ->with('message', 'Upps hubo un problema al guardar el Inmueble.');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request,$id)
    {
         $myProperty          = Realestate::findorFail($id);

         // Cargo el el array asociado a la sesion con la propiedades que va visitando el usuario
         session()->push('realestateId', ['id' => $myProperty->id, 'name' => $myProperty->name, 'price' => $myProperty->price, 'created_at' => $myProperty->created_at,'imageCover' => $myProperty->multimedia->where('main', 1) ]);
         
         $userId                 = $myProperty->user_id;
         $informationPersonal    = User::where('id', $userId)->get();
         $multimedia             = $this->getMultimedia($id);
         $propertyVideo          = $myProperty->video()->get();
         $Comments                = Comment::where('user_id',auth()->id())->where('realestate_id', $myProperty->id)->get();
         // Redes Sociales del Usuario y  celular
         $user                   = User::where('id', $userId)->get();
         $userCelular            = $user[0]->contact()->where('type_of_contact_id', 1)->get();
         $userFacebook           = $user[0]->contact()->where('type_of_contact_id', 4)->get();
         $userInstagram          = $user[0]->contact()->where('type_of_contact_id', 5)->get();
         // Propiedades visitadas recientemente
         $lastVisitedRealEstates = $this->lastVisitedRealEstates();
         // Propiedades Similares ubicadas en la misma localidad o provincia
         $similarProperties      = Realestate::where('locality_id',1)->orWhere('province_id',1)->get();

         $countMultimedia        = count($multimedia);
         $countProperties        = count($myProperty->option);

         return view('frontend.propertyDetails', compact('myProperty','informationPersonal','multimedia','countMultimedia','countProperties','userCelular', 'userFacebook','propertyVideo','userInstagram','lastVisitedRealEstates','similarProperties','Comments'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $idUser            = auth()->id();
        $user              = User::find($idUser);
    	$property 		   = Realestate::findorFail($id);
        $options           = Option::all();
        $countries         = Country::all();
        $provinces         = Province::all();
        $localities        = Localitie::all();
        $cities            = City::all();
        $states            = State::all();
        $typeOfRealestates = TypeOfRealestate::all();
        $celular           = $user->contact()->where('type_of_contact_id', 1)->get();

        return view('frontend.dashboard.property.edit', compact('property','options','countries','provinces','localities','cities','states','typeOfRealestates','celular'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {   


        $data = request()->validate([
            'propertyName'        => 'required',
            'price'               => 'required',
            'area'                => 'required',
            'bedrooms'            => 'required',
            'bathrooms'           => 'required',
            'address'             => 'required',

resources/views/frontend/dashboard/property/index.blade.php
@extends('frontend.dashboard.masterDashboard')

@section('stylus')
<style>

    .modal-confirm {        
        color: #636363;
        width: 400px;
    }
    .modal-confirm .modal-content {
        padding: 20px;
        border-radius: 5px;
        border: none;
        text-align: center;
        font-size: 14px;
    }
    .modal-confirm .modal-header {
        border-bottom: none;   
        position: relative;
    }
    .modal-confirm h4 {
        text-align: center;
        font-size: 26px;
        margin: 30px 0 -10px;
    }
    .modal-confirm .close {
        position: absolute;
        top: -5px;
        right: -2px;
    }
    .modal-confirm .modal-body {
        color: #999;
    }
    .modal-confirm .modal-footer {
        border: none;
        text-align: center;     
        border-radius: 5px;
        font-size: 13px;
        padding: 10px 15px 25px;
    }
    .modal-confirm .modal-footer a {
        color: #999;
    }       
    .modal-confirm .icon-box {
        width: 80px;
        height: 80px;
        margin: 0 auto;
        border-radius: 50%;
        z-index: 9;
        text-align: center;
        border: 3px solid #f15e5e;
    }
    .modal-confirm .icon-box i {
        color: #f15e5e;
        font-size: 46px;
        display: inline-block;
        margin-top: 13px;
    }
    .modal-confirm .btn {
        color: #fff;
        border-radius: 4px;
        background: #60c7c1;
        text-decoration: none;
        transition: all 0.4s;
        line-height: normal;
        min-width: 120px;
        border: none;
        min-height: 40px;
        border-radius: 3px;
        margin: 0 5px;
        outline: none !important;
    }
    .modal-confirm .btn-info {
        background: #c1c1c1;
    }
    .modal-confirm .btn-info:hover, .modal-confirm .btn-info:focus {
        background: #a8a8a8;
    }
    .modal-confirm .btn-danger {
        background: #f15e5e;
    }
    .modal-confirm .btn-danger:hover, .modal-confirm .btn-danger:focus {
        background: #ee3535;
    }
    .trigger-btn {
        display: inline-block;
        margin: 100px auto;
    }

</style>

@endsection


@section('content_dashboard')
        
<div class="dashboard-header clearfix">
        <div class="row">
            <div class="col-sm-12 col-md-6"><h4>Mi Propiedad</h4></div>
            <div class="col-sm-12 col-md-6">
                <div class="breadcrumb-nav">
                    <ul>
                        <li>
                            <a href="{{ url('/') }}">Inicio</a>
                        </li>
                        <li>
                            <a href="{{ url('panel') }}">Panel</a>
                        </li>
                        <li class="active">Mis Propiedades</li>
                    </ul>
                </div>
            </div>
        </div>
</div>
    @if (session('typemsg'))
        @if (session('typemsg') == 'success')
            <div class="alert alert-success" role="alert">
             <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
             </button>
                <strong>{{ session('message') }}</strong>
            </div>
        @endif
        @if (session('typemsg') == 'error' )
            <div class="alert alert-danger" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                 </button>
                <strong>{{ session('message') }}</strong>
            </div>
        @endif  
    @endif  
    <div class="dashboard-list">
        <h3>Lista de Mis Propiedades</h3>
        <table class="manage-table">
            <tbody>
            @foreach ($properties as $property)
                <tr class="responsive-table">
                    <td class="listing-photoo">
                        @foreach ($property->multimedia->where('main', 1) as $imageCover)
                            <img src="{{ asset('img/realestates/main/'.$imageCover->url.'') }}" alt="listing-photo" class="img-fluid">
                        @endforeach
                        
                                                
                    </td>
                    <td class="title-container">
                        <h2><a href="{{ route('propiedades.show', $property->id) }}">{{ $property->name  }}</a></h2>
                        <h5 class="d-none d-xl-block d-lg-block d-md-block"><i class="flaticon-pin"></i> {{ $property->address  }} </h5>
                        <h6 class="table-property-price">{{ $property->price .'/ '. $property->type_of_realestate->name  }} </h6>
                    </td>
                    <td class="expire-date">{{ $property->type_of_realestate->name }}</td>
                    <td class="action">
                        <a href="{{ route('propiedades.edit', $property->id) }}"><i class="fa fa-pencil"></i> Editar</a>
                        <a href="{{ route('propiedades.show', $property->id) }}"><i class="fa  fa-eye-slash"></i> Ver</a>
                        <a href="{{url('Multimedia/'.$property->id.'')}}"><i class="fa  fa-camera"></i> Cargar Imagenes</a>
                        <a  id="modalShow" data-toggle="modal" data-propid="{{ $property->id }}" data-target="#modalDelete"class="delete"><i class="fa fa-remove"></i> Eliminar</a>
                    </td>
                </tr>
             
            @endforeach
            </tbody>
        </table>
    </div>

@include('frontend.dashboard.modals.delete')
@endsection


@section('script')
<script>
     $('#modalDelete').on('show.bs.modal', function (event) {
        $("#modalDelete").css("margin", "100px");
        var button = $(event.relatedTarget) 
        var prop_id = button.data('propid') 
        var modal = $(this)
         modal.find('.modal-footer #prop_id').val(prop_id);
    })



</script>

@endsection